AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LamdaProject
  Sample SAM Template for LamdaProject

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600
    MemorySize: 128
    Tracing: Active
    Layers:
      - 'arn:aws:lambda:ap-northeast-2:123412341234:layer:common_aws:2'

Resources:
  LambdaAthena:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda_athena/
      FunctionName: lambda_athena
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 600
      Role: 'arn:aws:iam::123412341234:role/my-lambda-etl-role'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 23 ? * SUN *)

  LambdaS3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_s3/
      FunctionName: lambda_s3
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 600
      Role: 'arn:aws:iam::123412341234:role/my-lambda-etl-role'
      Events:
        DightyAppinstallEvent:
          Type: S3
          Properties:
            Bucket:
              - Name: my-bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: path/finished/job/      # The value to search for in the S3 object key names
                  - Name: suffix
                    Value: _SUCCESS      # The value to search for in the S3 object key names

  LambdaElasticsearch:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_elasticsearch/
      FunctionName: lambda_elasticsearch
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 600
      Role: 'arn:aws:iam::123412341234:role/my-lambda-etl-role'

  CommonAws:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./common_aws
      CompatibleRuntimes:
        - python3.9
        - python3.8
      LayerName: common_aws
      RetentionPolicy: Retain